### ISSUE TITLE
Stack2018 Workshop 

### ISSUE THREAD

**Issue by vinhnglx** [DevSecOpsSG/remove-secrets#45]
# Request

Add me to DevSecOpsSG Github Organizations

### A bit about yourself

Name : Vincent Nguyen

Email : vinh.nglx@gmail.com

Organization : SiliconJungles Pte Ltd

Others (Projects/Portfolio) : https://github.com/vinhnglx

**Comment by robincher** [comment]
Invite sent, please check.
