### ISSUE TITLE
stack 2018 

### ISSUE THREAD

**Issue by azmatparveen** [DevSecOpsSG/remove-secrets#46]
# Request

Add me to DevSecOpsSG Github Organizations

### A bit about yourself

Name :
azmat
Email :
azmatngg@hotmail.com
Organization :
PropertyGuru
Others (Projects/Portfolio) :

**Comment by robincher** [comment]
Please check,invite sent

**Comment by azmatparveen** [comment]
Hi ,
I have sent a wrong the email. Sorry could you please resend it on azmatengg@hotmail.com
